# Generated by Django 4.1.5 on 2023-01-20 14:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Snacks', '0014_alter_comment_sternbewertung'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField(default=django.utils.timezone.now)),
                ('benutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produkt_id', models.IntegerField()),
                ('produkt_name', models.CharField(max_length=100)),
                ('preis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menge', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('shopping_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shoppingcart.shoppingcart')),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Snacks.snack')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kreditkartenr', models.CharField(max_length=19)),
                ('ablaufsdatum', models.CharField(max_length=7)),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zeitstempel', models.DateTimeField(default=django.utils.timezone.now)),
                ('benutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
