# Generated by Django 4.1.5 on 2023-01-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shoppingcart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='snack',
        ),
    ]
