# Generated by Django 4.1.3 on 2022-11-30 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gewicht', models.IntegerField()),
                ('beschreibung', models.CharField(blank=True, max_length=1000)),
                ('artikelnummer', models.CharField(max_length=100)),
                ('preis', models.FloatField(max_length=50)),
                ('erstellungs_zeitstempel', models.DateTimeField(auto_now_add=True)),
                ('hersteller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hersteller', related_query_name='Hersteller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Snacks',
                'verbose_name_plural': 'Snacks',
                'ordering': ['erstellungs_zeitstempel', 'name'],
            },
        ),
    ]
