# Generated by Django 4.1.3 on 2022-12-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sternbewertung',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=1),
        ),
        migrations.AlterField(
            model_name='snack',
            name='pictures',
            field=models.ImageField(blank=True, default='snack_pictures/white-background-2.jpg', null=True, upload_to='snack_pictures/'),
        ),
    ]
