# Generated by Django 4.1.3 on 2022-12-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snacks', '0002_comment_sternbewertung_alter_snack_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='produkt_info',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/'),
        ),
    ]
