# Generated by Django 4.1.3 on 2022-11-30 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Snacks', '0002_snack_pictures_alter_snack_preis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_or_down', models.CharField(choices=[('U', 'up'), ('D', 'down')], max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Snacks.snack')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Voter', related_query_name='Voters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Poster', related_query_name='Posters', to=settings.AUTH_USER_MODEL)),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Snacks.snack')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['timestamp'],
            },
        ),
    ]
