# Generated by Django 4.1.3 on 2022-12-10 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Snacks', '0003_snack_produkt_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='pictures',
            new_name='bilder',
        ),
    ]
