# Generated by Django 4.1.4 on 2022-12-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snacks', '0004_rename_pictures_snack_bilder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='produkt_info',
            field=models.FileField(blank=True, default='uploaded_files/Kalender_2022_2023.pdf', null=True, upload_to='uploaded_files/'),
        ),
    ]
