# Generated by Django 4.1.3 on 2023-01-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snacks', '0008_alter_comment_sternbewertung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='sternbewertung',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
    ]
