# Generated by Django 4.1.5 on 2023-01-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snacks', '0011_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='produkt_bewertung',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='snack',
            name='produkt_info',
            field=models.FileField(blank=True, default='uploaded_files/empty.pdf', null=True, upload_to='uploaded_files/'),
        ),
    ]
