# Generated by Django 4.1.5 on 2023-01-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snacks', '0014_alter_comment_sternbewertung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='produkt_bewertung',
            field=models.FloatField(default=0),
        ),
    ]
